### ISSUE TITLE
[✗] Fatal error: 'bd'

### ISSUE THREAD

**Issue by imverynewhere** [ramseymcgrath/PCILeechFWGenerator#42]
ubuntu@ubuntu:~/Downloads/PCILeechFWGenerator-main$ sudo python3 generate.py 

2025-06-14 21:36:23,861 - ERROR - Fatal error during firmware generation: 'bd'

[✗] Fatal error: 'bd'

**Comment by ramseymcgrath** [comment]
resolved by https://github.com/ramseymcgrath/PCILeechFWGenerator/pull/43

**Comment by Brudderhood** [comment]
Hello @ramseymcgrath ,

I downloaded the latest files and still get the same fatal error "BD"

Is it okay if I contact you on discord? I added a few days ago but didn't wanna be rude and message for help.
